### ISSUE TITLE
potential bug

### ISSUE THREAD

**Issue by dwaithe** [WeidiXie/cell_counting_v2#1]
mean_diff = (np.sum(A) - np.sum(val_anno)) / (100.0 * val_anno.shape[0] )
print('After training, the difference is : {} cells per image.'.format(np.abs(mean_diff)))

Your mean_diff formula is absolute mean difference. It should be mean absolute difference? We don't want negative difference to cancel positive?
Should be:
mean_diff = np.average(np.abs(np.sum(np.sum(A,1),1)-np.sum(np.sum(val_anno,1),1))) / (100.0)
print('After training, the difference is : {} cells per image.'.format((mean_diff)))

**Comment by WeidiXie** [comment]
Oh, yes, you are right. To calculate the final accuracy it should be calculated for each image individually.
