### ISSUE TITLE
How many cells are on picture

### ISSUE THREAD

**Issue by AlexunderMicrocontrol** [WeidiXie/cell_counting_v2#3]
Hi Weidi it's not really an issue. Your code works fine but you are meassure the difference. Is there way to get the number of cells are on picture ??

**Comment by WeidiXie** [comment]
Hi, 

Once you get the predictions, simply summing up the absolute values will give you the number of cells in the image.

BW
Weidi

**Comment by AlexunderMicrocontrol** [comment]
Ok thx.
