### ISSUE TITLE
Why we take the absolute of the predictions.

### ISSUE THREAD

**Issue by sagarkar10** [WeidiXie/cell_counting_v2#7]
Not an Issue, but a request to explain.
Please explain the generation of negative numbers in the prediction. Ideally, should it not be all between 0-100. I understand during optimizing the negative numbers can come. I would appreciate if you can also explain the idea of summing up the absolute (#3 ) of the prediction and not only the positive numbers.
Excuse me if that was very trivial.
@WeidiXie

**Comment by WeidiXie** [comment]
No, just take the sum of the prediction maps should give you the number of cells.
