### ISSUE TITLE
How to escape all zeros prediction?

### ISSUE THREAD

**Issue by mrgloom** [WeidiXie/cell_counting_v2#9]
How to escape all zero prediction?

I use 128x128 input and seems network converges to all zeros prediction.

Here I have similar issue for semantic segmentation task, but it arises only for larger image size(512x512)
https://github.com/ZFTurbo/ZF_UNET_224_Pretrained_Model/issues/10

Also I see some multiplier `100.0` in our code, is it crucial to network convergence? Also after applying gaussian smoothing max value will lower about `16`.
https://github.com/WeidiXie/cell_counting_v2/blob/d37bf7048120faf958a51930bfe9e558206faaa0/train.py#L53

**Comment by WeidiXie** [comment]
That's because your gt map has too many zeros, 
so, the model doesn't need to learn anything, always predicting 0s, will give very low loss already.

The multiplier in the code is simply used for weighted loss, because now, if you predict 0s at the position where gt is 100, the network will be penalised a lot.

There are other ideas you can try, for example, you can computer masked losses, 
meaning for the positions where gt = 0, you simply randomise a mask and compute losses for some of them. Anyway, as long as you can balance the classes, it will avoid all zero predictions.

**Comment by mrgloom** [comment]
I have run several experiments with different loss functions, in my setting only one pixel on image is not zero.

Here is some results:

```
bce loss :
Pipeline: mask in range [0,1] as single pixel + sigmoid + bce loss -> Fail
Pipeline: mask in range [0,1] as blob + sigmoid + bce loss -> Ok

weighted bce loss :
Pipeline: mask in range [0,1] as single pixel + sigmoid + weighted bce loss -> Ok [Comment: converges not to single point but to blob]

mae loss :
Pipeline: mask in range [0,1] as single pixel + linear activation + mae loss -> Fail
Pipeline: mask in range [0,1] as single pixel + multiplier + linear activation + mae loss -> Fail
Pipeline: mask in range [0,1] as single pixel + multiplier + relu activation + mae loss -> Fail
Pipeline: mask in range [0,1] as single pixel + sigmoid activation + mae loss -> Fail
Pipeline: mask in range [0,1] as single pixel + BN + linear activation + mae loss -> Fail

mse loss : 
Pipeline: mask in range [0,1] as single pixel + BN + linear activation + mse loss -> Fail [Comment: activations not zero pred_min: -0.0097 - pred_max: 0.0117 and y_true_sum: 16.0000, y_pred_sum: 16.0000]
Pipeline: mask in range [0,1] as single pixel + multiplier + BN + linear activation + mse loss -> Fail [Comment: converges to constant y_true_sum: 262128.0000 - y_pred_sum: 262127.0678 , nans in val_loss]
```

Here is the project to reproduce results:
https://github.com/mrgloom/random_code_samples/tree/master/DL/unet_loss_experiment

I'm using simple version of Unet: https://github.com/mrgloom/random_code_samples/blob/master/DL/unet_loss_experiment/custom_model.py#L4

So as I understand just weighting is not sufficient, is there any other key components in pipeline that I'm missing?
